# Generated by Django 5.2.15 on 2026-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CONTACTED', 'CONTACTED'), ('QUALIFIED', 'QUALIFIED'), ('PROPOSAL', 'PROPOSAL'), ('WON', 'WON'), ('LOST', 'LOST')], db_index=True, default='NEW', max_length=20),
        ),
    ]
