# Generated by Django 5.2.15 on 2026-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_created_at_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('SALES', 'SALES'), ('HOSPITAL', 'HOSPITAL'), ('RESTAURANTS', 'RESTAURANTS'), ('OTHER', 'OTHER')], db_index=True, default='SALES', max_length=50),
        ),
    ]
