# Generated by Django 5.2.15 on 2026-06-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stage', models.CharField(choices=[('DISCOVERY', 'DISCOVERY'), ('DEMO', 'DEMO'), ('NEGOTIATION', 'NEGOTIATION'), ('CLOSED_WON', 'CLOSED_WON'), ('CLOSED_LOST', 'CLOSED_LOST')], default='DISCOVERY', max_length=50)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='leads.lead')),
            ],
        ),
    ]
