# Generated by Django 5.2.15 on 2026-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('DISCOVERY', 'DISCOVERY'), ('DEMO', 'DEMO'), ('NEGOTIATION', 'NEGOTIATION'), ('CLOSED_WON', 'CLOSED_WON'), ('CLOSED_LOST', 'CLOSED_LOST')], db_index=True, default='DISCOVERY', max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
    ]
